import {
  afterEach,
  describe, expect, it, MockedFunction, vi,
} from 'vitest';
import {
  fileURLToPath,
} from 'node:url';
import {
  setup,
} from '@nuxt/test-utils/e2e';
import {
  useLegalHoliday,
} from '../src/runtime/server/composables/useLegalHoliday';
import {
  useLegalHolidayClient,
} from '../src/runtime/server/useLegalHolidayClient';
import * as dataHandler from './fixtures/basic/server/datasources/dataHandler';

vi.mock('./fixtures/basic/server/datasources/dataHandler', () => ({
  default: {
    findData: vi.fn(),
    saveData: vi.fn(),
  },
}));
vi.mock('../src/runtime/server/useLegalHolidayClient', () => ({
  useLegalHolidayClient: vi.fn(),
}));

describe('useLegalHoliday', async () => {
  await setup({
    rootDir: fileURLToPath(new URL('./fixtures/basic', import.meta.url)),
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should fetch holidays from API if DataHandler is empty', async () => {
    const findDataSpy = (dataHandler.default.findData as MockedFunction<typeof dataHandler.default.findData>).mockImplementationOnce(async () => {
      return null;
    });
    const saveDataSpy = (dataHandler.default.saveData as MockedFunction<typeof dataHandler.default.saveData>).mockImplementationOnce(async () => {
      return null;
    });
    const getLegalHolidaysSpy = (useLegalHolidayClient as MockedFunction<typeof useLegalHolidayClient>).mockImplementationOnce(() => {
      return {
        getLegalHolidays: () => ({
          2025:{
            cacheDate:'2025-09-29T10:53:27.102Z',
            legalHolidays:[
              {
                date:'2025-01-01',
                name:'Neujahr',
                all_states:'1',
                bw:'1',
                by:'1',
                be:'1',
                bb:'1',
                hb:'1',
                hh:'1',
                he:'1',
                mv:'1',
                ni:'1',
                nw:'1',
                rp:'1',
                sl:'1',
                sn:'1',
                st:'1',
                sh:'1',
                th:'1',
                augsburg:false,
              },
              {
                date:'2025-01-06',
                name:'Heilige Drei Könige',
                all_states:'0',
                bw:'1',
                by:'1',
                be:'0',
                bb:'0',
                hb:'0',
                hh:'0',
                he:'0',
                mv:'0',
                ni:'0',
                nw:'0',
                rp:'0',
                sl:'0',
                sn:'0',
                st:'1',
                sh:'0',
                th:'0',
                augsburg:false,
              },
              {
                date:'2025-03-08',
                name:'Internationaler Frauentag',
                all_states:'0',
                bw:'0',
                by:'0',
                be:'1',
                bb:'0',
                hb:'0',
                hh:'0',
                he:'0',
                mv:'1',
                ni:'0',
                nw:'0',
                rp:'0',
                sl:'0',
                sn:'0',
                st:'0',
                sh:'0',
                th:'0',
                augsburg:false,
              },
              {
                date:'2025-04-18',
                name:'Karfreitag',
                all_states:'1',
                bw:'1',
                by:'1',
                be:'1',
                bb:'1',
                hb:'1',
                hh:'1',
                he:'1',
                mv:'1',
                ni:'1',
                nw:'1',
                rp:'1',
                sl:'1',
                sn:'1',
                st:'1',
                sh:'1',
                th:'1',
                augsburg:false,
              },
              {
                date:'2025-04-20',
                name:'Ostersonntag',
                all_states:'0',
                bw:'0',
                by:'0',
                be:'0',
                bb:'1',
                hb:'0',
                hh:'0',
                he:'0',
                mv:'0',
                ni:'0',
                nw:'0',
                rp:'0',
                sl:'0',
                sn:'0',
                st:'0',
                sh:'0',
                th:'0',
                augsburg:false,
              },
              {
                date:'2025-04-21',
                name:'Ostermontag',
                all_states:'1',
                bw:'1',
                by:'1',
                be:'1',
                bb:'1',
                hb:'1',
                hh:'1',
                he:'1',
                mv:'1',
                ni:'1',
                nw:'1',
                rp:'1',
                sl:'1',
                sn:'1',
                st:'1',
                sh:'1',
                th:'1',
                augsburg:false,
              },
              {
                date:'2025-05-01',
                name:'Tag der Arbeit',
                all_states:'1',
                bw:'1',
                by:'1',
                be:'1',
                bb:'1',
                hb:'1',
                hh:'1',
                he:'1',
                mv:'1',
                ni:'1',
                nw:'1',
                rp:'1',
                sl:'1',
                sn:'1',
                st:'1',
                sh:'1',
                th:'1',
                augsburg:false,
              },
              {
                date:'2025-05-08',
                name:'80. Jahrestag der Befreiung vom Nationalsozialismus',
                all_states:'0',
                bw:'0',
                by:'0',
                be:'1',
                bb:'0',
                hb:'0',
                hh:'0',
                he:'0',
                mv:'0',
                ni:'0',
                nw:'0',
                rp:'0',
                sl:'0',
                sn:'0',
                st:'0',
                sh:'0',
                th:'0',
                augsburg:false,
              },
              {
                date:'2025-05-29',
                name:'Christi Himmelfahrt',
                all_states:'1',
                bw:'1',
                by:'1',
                be:'1',
                bb:'1',
                hb:'1',
                hh:'1',
                he:'1',
                mv:'1',
                ni:'1',
                nw:'1',
                rp:'1',
                sl:'1',
                sn:'1',
                st:'1',
                sh:'1',
                th:'1',
                augsburg:false,
              },
              {
                date:'2025-06-08',
                name:'Pfingstsonntag',
                all_states:'0',
                bw:'0',
                by:'0',
                be:'0',
                bb:'1',
                hb:'0',
                hh:'0',
                he:'0',
                mv:'0',
                ni:'0',
                nw:'0',
                rp:'0',
                sl:'0',
                sn:'0',
                st:'0',
                sh:'0',
                th:'0',
                augsburg:false,
              },
              {
                date:'2025-06-09',
                name:'Pfingstmontag',
                all_states:'1',
                bw:'1',
                by:'1',
                be:'1',
                bb:'1',
                hb:'1',
                hh:'1',
                he:'1',
                mv:'1',
                ni:'1',
                nw:'1',
                rp:'1',
                sl:'1',
                sn:'1',
                st:'1',
                sh:'1',
                th:'1',
                augsburg:false,
              },
              {
                date:'2025-06-19',
                name:'Fronleichnam',
                all_states:'0',
                bw:'1',
                by:'1',
                be:'0',
                bb:'0',
                hb:'0',
                hh:'0',
                he:'1',
                mv:'0',
                ni:'0',
                nw:'1',
                rp:'1',
                sl:'1',
                sn:'0',
                st:'0',
                sh:'0',
                th:'0',
                augsburg:false,
              },
              {
                date:'2025-08-08',
                name:'Augsburger Friedensfest',
                all_states:'0',
                bw:'0',
                by:'1',
                be:'0',
                bb:'0',
                hb:'0',
                hh:'0',
                he:'0',
                mv:'0',
                ni:'0',
                nw:'0',
                rp:'0',
                sl:'0',
                sn:'0',
                st:'0',
                sh:'0',
                th:'0',
                augsburg:true,
              },
              {
                date:'2025-08-15',
                name:'Mariä Himmelfahrt',
                all_states:'0',
                bw:'0',
                by:'1',
                be:'0',
                bb:'0',
                hb:'0',
                hh:'0',
                he:'0',
                mv:'0',
                ni:'0',
                nw:'0',
                rp:'0',
                sl:'1',
                sn:'0',
                st:'0',
                sh:'0',
                th:'0',
                augsburg:false,
              },
              {
                date:'2025-09-20',
                name:'Weltkindertag',
                all_states:'0',
                bw:'0',
                by:'0',
                be:'0',
                bb:'0',
                hb:'0',
                hh:'0',
                he:'0',
                mv:'0',
                ni:'0',
                nw:'0',
                rp:'0',
                sl:'0',
                sn:'0',
                st:'0',
                sh:'0',
                th:'1',
                augsburg:false,
              },
              {
                date:'2025-10-03',
                name:'Tag der deutschen Einheit',
                all_states:'1',
                bw:'1',
                by:'1',
                be:'1',
                bb:'1',
                hb:'1',
                hh:'1',
                he:'1',
                mv:'1',
                ni:'1',
                nw:'1',
                rp:'1',
                sl:'1',
                sn:'1',
                st:'1',
                sh:'1',
                th:'1',
                augsburg:false,
              },
              {
                date:'2025-10-31',
                name:'Reformationstag',
                all_states:'0',
                bw:'0',
                by:'0',
                be:'0',
                bb:'1',
                hb:'1',
                hh:'1',
                he:'0',
                mv:'1',
                ni:'1',
                nw:'0',
                rp:'0',
                sl:'0',
                sn:'1',
                st:'1',
                sh:'1',
                th:'1',
                augsburg:false,
              },
              {
                date:'2025-11-01',
                name:'Allerheiligen',
                all_states:'0',
                bw:'1',
                by:'1',
                be:'0',
                bb:'0',
                hb:'0',
                hh:'0',
                he:'0',
                mv:'0',
                ni:'0',
                nw:'1',
                rp:'1',
                sl:'1',
                sn:'0',
                st:'0',
                sh:'0',
                th:'0',
                augsburg:false,
              },
              {
                date:'2025-11-19',
                name:'Buß- und Bettag',
                all_states:'0',
                bw:'0',
                by:'0',
                be:'0',
                bb:'0',
                hb:'0',
                hh:'0',
                he:'0',
                mv:'0',
                ni:'0',
                nw:'0',
                rp:'0',
                sl:'0',
                sn:'1',
                st:'0',
                sh:'0',
                th:'0',
                augsburg:false,
              },
              {
                date:'2025-12-25',
                name:'1. Weihnachtstag',
                all_states:'1',
                bw:'1',
                by:'1',
                be:'1',
                bb:'1',
                hb:'1',
                hh:'1',
                he:'1',
                mv:'1',
                ni:'1',
                nw:'1',
                rp:'1',
                sl:'1',
                sn:'1',
                st:'1',
                sh:'1',
                th:'1',
                augsburg:false,
              },
              {
                date:'2025-12-26',
                name:'2. Weihnachtstag',
                all_states:'1',
                bw:'1',
                by:'1',
                be:'1',
                bb:'1',
                hb:'1',
                hh:'1',
                he:'1',
                mv:'1',
                ni:'1',
                nw:'1',
                rp:'1',
                sl:'1',
                sn:'1',
                st:'1',
                sh:'1',
                th:'1',
                augsburg:false,
              },
            ],
          },
        }),
      };
    });

    const {
      getLegalHoliday,
    } = useLegalHoliday();
    const result = await getLegalHoliday(2025);

    expect(result).toEqual([
      {
        date: '2025-01-01',
        name: 'Neujahr',
      },
      {
        date: '2025-01-06',
        name: 'Heilige Drei Könige',
      },
      {
        date: '2025-03-08',
        name: 'Internationaler Frauentag',
      },
      {
        date: '2025-04-18',
        name: 'Karfreitag',
      },
      {
        date: '2025-04-20',
        name: 'Ostersonntag',
      },
      {
        date: '2025-04-21',
        name: 'Ostermontag',
      },
      {
        date: '2025-05-01',
        name: 'Tag der Arbeit',
      },
      {
        date: '2025-05-08',
        name: '80. Jahrestag der Befreiung vom Nationalsozialismus',
      },
      {
        date: '2025-05-29',
        name: 'Christi Himmelfahrt',
      },
      {
        date: '2025-06-08',
        name: 'Pfingstsonntag',
      },
      {
        date: '2025-06-09',
        name: 'Pfingstmontag',
      },
      {
        date: '2025-06-19',
        name: 'Fronleichnam',
      },
      {
        date: '2025-08-15',
        name: 'Mariä Himmelfahrt',
      },
      {
        date: '2025-09-20',
        name: 'Weltkindertag',
      },
      {
        date: '2025-10-03',
        name: 'Tag der deutschen Einheit',
      },
      {
        date: '2025-10-31',
        name: 'Reformationstag',
      },
      {
        date: '2025-11-01',
        name: 'Allerheiligen',
      },
      {
        date: '2025-11-19',
        name: 'Buß- und Bettag',
      },
      {
        date: '2025-12-25',
        name: '1. Weihnachtstag',
      },
      {
        date: '2025-12-26',
        name: '2. Weihnachtstag',
      },
    ]);
    expect(findDataSpy).toHaveBeenCalled();
    expect(getLegalHolidaysSpy).toHaveBeenCalled();
    expect(saveDataSpy).toHaveBeenCalled();
  });

  it('should return holidays from DataHandler if available', async () => {
    const findDataSpy = (dataHandler.default.findData as MockedFunction<typeof dataHandler.default.findData>).mockImplementationOnce(async () => {
      return {
        2024:{
          cacheDate:'2025-09-29T12:05:21.532Z',
          legalHolidays:[
            {
              date:'2024-01-01',
              name:'Neujahr',
              all_states:'1',
              bw:'1',
              by:'1',
              be:'1',
              bb:'1',
              hb:'1',
              hh:'1',
              he:'1',
              mv:'1',
              ni:'1',
              nw:'1',
              rp:'1',
              sl:'1',
              sn:'1',
              st:'1',
              sh:'1',
              th:'1',
              augsburg:false,
            },
            {
              date:'2024-01-06',
              name:'Heilige Drei Könige',
              all_states:'0',
              bw:'1',
              by:'1',
              be:'0',
              bb:'0',
              hb:'0',
              hh:'0',
              he:'0',
              mv:'0',
              ni:'0',
              nw:'0',
              rp:'0',
              sl:'0',
              sn:'0',
              st:'1',
              sh:'0',
              th:'0',
              augsburg:false,
            },
            {
              date:'2024-03-08',
              name:'Internationaler Frauentag',
              all_states:'0',
              bw:'0',
              by:'0',
              be:'1',
              bb:'0',
              hb:'0',
              hh:'0',
              he:'0',
              mv:'1',
              ni:'0',
              nw:'0',
              rp:'0',
              sl:'0',
              sn:'0',
              st:'0',
              sh:'0',
              th:'0',
              augsburg:false,
            },
            {
              date:'2024-03-29',
              name:'Karfreitag',
              all_states:'1',
              bw:'1',
              by:'1',
              be:'1',
              bb:'1',
              hb:'1',
              hh:'1',
              he:'1',
              mv:'1',
              ni:'1',
              nw:'1',
              rp:'1',
              sl:'1',
              sn:'1',
              st:'1',
              sh:'1',
              th:'1',
              augsburg:false,
            },
            {
              date:'2024-03-31',
              name:'Ostersonntag',
              all_states:'0',
              bw:'0',
              by:'0',
              be:'0',
              bb:'1',
              hb:'0',
              hh:'0',
              he:'0',
              mv:'0',
              ni:'0',
              nw:'0',
              rp:'0',
              sl:'0',
              sn:'0',
              st:'0',
              sh:'0',
              th:'0',
              augsburg:false,
            },
            {
              date:'2024-04-01',
              name:'Ostermontag',
              all_states:'1',
              bw:'1',
              by:'1',
              be:'1',
              bb:'1',
              hb:'1',
              hh:'1',
              he:'1',
              mv:'1',
              ni:'1',
              nw:'1',
              rp:'1',
              sl:'1',
              sn:'1',
              st:'1',
              sh:'1',
              th:'1',
              augsburg:false,
            },
            {
              date:'2024-05-01',
              name:'Tag der Arbeit',
              all_states:'1',
              bw:'1',
              by:'1',
              be:'1',
              bb:'1',
              hb:'1',
              hh:'1',
              he:'1',
              mv:'1',
              ni:'1',
              nw:'1',
              rp:'1',
              sl:'1',
              sn:'1',
              st:'1',
              sh:'1',
              th:'1',
              augsburg:false,
            },
            {
              date:'2024-05-09',
              name:'Christi Himmelfahrt',
              all_states:'1',
              bw:'1',
              by:'1',
              be:'1',
              bb:'1',
              hb:'1',
              hh:'1',
              he:'1',
              mv:'1',
              ni:'1',
              nw:'1',
              rp:'1',
              sl:'1',
              sn:'1',
              st:'1',
              sh:'1',
              th:'1',
              augsburg:false,
            },
            {
              date:'2024-05-19',
              name:'Pfingstsonntag',
              all_states:'0',
              bw:'0',
              by:'0',
              be:'0',
              bb:'1',
              hb:'0',
              hh:'0',
              he:'0',
              mv:'0',
              ni:'0',
              nw:'0',
              rp:'0',
              sl:'0',
              sn:'0',
              st:'0',
              sh:'0',
              th:'0',
              augsburg:false,
            },
            {
              date:'2024-05-20',
              name:'Pfingstmontag',
              all_states:'1',
              bw:'1',
              by:'1',
              be:'1',
              bb:'1',
              hb:'1',
              hh:'1',
              he:'1',
              mv:'1',
              ni:'1',
              nw:'1',
              rp:'1',
              sl:'1',
              sn:'1',
              st:'1',
              sh:'1',
              th:'1',
              augsburg:false,
            },
            {
              date:'2024-05-30',
              name:'Fronleichnam',
              all_states:'0',
              bw:'1',
              by:'1',
              be:'0',
              bb:'0',
              hb:'0',
              hh:'0',
              he:'1',
              mv:'0',
              ni:'0',
              nw:'1',
              rp:'1',
              sl:'1',
              sn:'0',
              st:'0',
              sh:'0',
              th:'0',
              augsburg:false,
            },
            {
              date:'2024-08-08',
              name:'Augsburger Friedensfest',
              all_states:'0',
              bw:'0',
              by:'1',
              be:'0',
              bb:'0',
              hb:'0',
              hh:'0',
              he:'0',
              mv:'0',
              ni:'0',
              nw:'0',
              rp:'0',
              sl:'0',
              sn:'0',
              st:'0',
              sh:'0',
              th:'0',
              augsburg:true,
            },
            {
              date:'2024-08-15',
              name:'Mariä Himmelfahrt',
              all_states:'0',
              bw:'0',
              by:'1',
              be:'0',
              bb:'0',
              hb:'0',
              hh:'0',
              he:'0',
              mv:'0',
              ni:'0',
              nw:'0',
              rp:'0',
              sl:'1',
              sn:'0',
              st:'0',
              sh:'0',
              th:'0',
              augsburg:false,
            },
            {
              date:'2024-09-20',
              name:'Weltkindertag',
              all_states:'0',
              bw:'0',
              by:'0',
              be:'0',
              bb:'0',
              hb:'0',
              hh:'0',
              he:'0',
              mv:'0',
              ni:'0',
              nw:'0',
              rp:'0',
              sl:'0',
              sn:'0',
              st:'0',
              sh:'0',
              th:'1',
              augsburg:false,
            },
            {
              date:'2024-10-03',
              name:'Tag der deutschen Einheit',
              all_states:'1',
              bw:'1',
              by:'1',
              be:'1',
              bb:'1',
              hb:'1',
              hh:'1',
              he:'1',
              mv:'1',
              ni:'1',
              nw:'1',
              rp:'1',
              sl:'1',
              sn:'1',
              st:'1',
              sh:'1',
              th:'1',
              augsburg:false,
            },
            {
              date:'2024-10-31',
              name:'Reformationstag',
              all_states:'0',
              bw:'0',
              by:'0',
              be:'0',
              bb:'1',
              hb:'1',
              hh:'1',
              he:'0',
              mv:'1',
              ni:'1',
              nw:'0',
              rp:'0',
              sl:'0',
              sn:'1',
              st:'1',
              sh:'1',
              th:'1',
              augsburg:false,
            },
            {
              date:'2024-11-01',
              name:'Allerheiligen',
              all_states:'0',
              bw:'1',
              by:'1',
              be:'0',
              bb:'0',
              hb:'0',
              hh:'0',
              he:'0',
              mv:'0',
              ni:'0',
              nw:'1',
              rp:'1',
              sl:'1',
              sn:'0',
              st:'0',
              sh:'0',
              th:'0',
              augsburg:false,
            },
            {
              date:'2024-11-20',
              name:'Buß- und Bettag',
              all_states:'0',
              bw:'0',
              by:'0',
              be:'0',
              bb:'0',
              hb:'0',
              hh:'0',
              he:'0',
              mv:'0',
              ni:'0',
              nw:'0',
              rp:'0',
              sl:'0',
              sn:'1',
              st:'0',
              sh:'0',
              th:'0',
              augsburg:false,
            },
            {
              date:'2024-12-25',
              name:'1. Weihnachtstag',
              all_states:'1',
              bw:'1',
              by:'1',
              be:'1',
              bb:'1',
              hb:'1',
              hh:'1',
              he:'1',
              mv:'1',
              ni:'1',
              nw:'1',
              rp:'1',
              sl:'1',
              sn:'1',
              st:'1',
              sh:'1',
              th:'1',
              augsburg:false,
            },
            {
              date:'2024-12-26',
              name:'2. Weihnachtstag',
              all_states:'1',
              bw:'1',
              by:'1',
              be:'1',
              bb:'1',
              hb:'1',
              hh:'1',
              he:'1',
              mv:'1',
              ni:'1',
              nw:'1',
              rp:'1',
              sl:'1',
              sn:'1',
              st:'1',
              sh:'1',
              th:'1',
              augsburg:false,
            },
          ],
        },
      };
    });
    const getLegalHolidaysSpy = (useLegalHolidayClient as MockedFunction<typeof useLegalHolidayClient>).mockImplementationOnce(() => {
      return null;
    });

    const {
      getLegalHoliday,
    } = useLegalHoliday();
    const result = await getLegalHoliday(2024);

    expect(result).toEqual([
      {
        date: '2024-01-01',
        name: 'Neujahr',
      },
      {
        date: '2024-01-06',
        name: 'Heilige Drei Könige',
      },
      {
        date: '2024-03-08',
        name: 'Internationaler Frauentag',
      },
      {
        date: '2024-03-29',
        name: 'Karfreitag',
      },
      {
        date: '2024-03-31',
        name: 'Ostersonntag',
      },
      {
        date: '2024-04-01',
        name: 'Ostermontag',
      },
      {
        date: '2024-05-01',
        name: 'Tag der Arbeit',
      },
      {
        date: '2024-05-09',
        name: 'Christi Himmelfahrt',
      },
      {
        date: '2024-05-19',
        name: 'Pfingstsonntag',
      },
      {
        date: '2024-05-20',
        name: 'Pfingstmontag',
      },
      {
        date: '2024-05-30',
        name: 'Fronleichnam',
      },
      {
        date: '2024-08-15',
        name: 'Mariä Himmelfahrt',
      },
      {
        date: '2024-09-20',
        name: 'Weltkindertag',
      },
      {
        date: '2024-10-03',
        name: 'Tag der deutschen Einheit',
      },
      {
        date: '2024-10-31',
        name: 'Reformationstag',
      },
      {
        date: '2024-11-01',
        name: 'Allerheiligen',
      },
      {
        date: '2024-11-20',
        name: 'Buß- und Bettag',
      },
      {
        date: '2024-12-25',
        name: '1. Weihnachtstag',
      },
      {
        date: '2024-12-26',
        name: '2. Weihnachtstag',
      },
    ]);

    expect(findDataSpy).toHaveBeenCalled();
    expect(getLegalHolidaysSpy).not.toHaveBeenCalled();
  });

  // TODO:: Check getting legal holidays by state are correct
  // TODO:: Check getting augsburg specific legal holiday
});
